### ISSUE TITLE
when call window.plugins.calllog.list() result is undefined

### ISSUE THREAD

**Issue by pratap477** [dalyc/Cordova-CallLog-Plugin#1]
My project is I have to get the calllog history from phone and send to the server.I don't get the calllog history by using calllog plugin, but I am new to cordova I don't know how to get the values in the script file.Can anybody pls help me..I have posted my code here.

But when call window.plugins.calllog.list() result is undefied

Please help me. I had search many site but not geting any anwser

**Comment by dalyc** [comment]
Be aware that this will only work on and Android device.
It won't work on an iphone.

**Comment by varunnayyar76** [comment]
How to use this plugin in cordova app
Please add README file with your project

**Comment by dalyc** [comment]
Hi @varunnayyar 

I apologise for not having a README - Originally, I created this project for my own use to test call log on Android. I will try to get some time over the next few days to add a README.

Cheers
dalyc

**Comment by varunnayyar76** [comment]
@dalyc thanks a lot :)

**Comment by smartbill** [comment]
Hi mate
A bit more info how to use your plugin in plain JS will be much appreciated. I use Telerik App builder and the plugin seams to be instaled correctly but when I do:

document.addEventListener("deviceready", loadLogs, false);

function loadLogs() {
console.log(window.plugins.calllog.list());
}; 

I get: Uncaught TypeError: Cannot read property 'calllog' of undefined

**Comment by komalbadge** [comment]
I did not getting a call log...please help me..thanks
