### ISSUE TITLE
Not able to install 

### ISSUE THREAD

**Issue by anujsphinx** [dalyc/Cordova-CallLog-Plugin#19]
hello Sir,
 I am getting issue .i  have attached image .is this plugin working ?
![plugin _issue](https://cloud.githubusercontent.com/assets/17042493/16644266/50c28c6e-4439-11e6-946c-433499f239b8.PNG)

**Comment by dalyc** [comment]
The project is the process of changing owners from dalyc to uriva so use
cordova plugins add "https://github.com/dalyc/Cordova-CallLog-Plugin"

soon this will become 
cordova plugins add "https://github.com/uriva/Cordova-CallLog-Plugin"

**Comment by anujsphinx** [comment]
Thx fro help .
  I installed it now then getting error of permission so i updated  android now it is working .I am getting one more error on console .
Uncaught SyntaxError: Unexpected token delete  
![deleet_error](https://cloud.githubusercontent.com/assets/17042493/16650009/83334772-4459-11e6-9c75-ec011e28c926.PNG)

after removing that delete code section 
     delete : function(phoneNumber) {
            var q = $q.defer();
            window.plugins.calllog.delete(id, function (response) {
                q.resolve(response);
            }, function (error) {
                q.reject(error)
            });
            return q.promise;
        }
 i am getting error  Error: [$injector:unpr] Unknown provider: LocalStorageProvider <- LocalStorage <- DebugCtrl

**Comment by anujsphinx** [comment]
After removing delete portion and LocalStorageProvider  i got the last call details.
Thanks

**Comment by dalyc** [comment]
I don't maintain this project anymore and just accepted a pull request with that delete code - if it causing problems I will remove it

**Comment by mv1994cs** [comment]
"https://github.com/dalyc/Cordova-CallLog-Plugin" i am unable to install this plugin please help me????

**Comment by codenoid** [comment]
make your own plugin

and tell me, i will use it xD
