### ISSUE TITLE
Using Provided Demo

### ISSUE THREAD

**Issue by smartbill** [dalyc/Cordova-CallLog-Plugin#2]
## Hi I've tried to use your demo code with Angular JS within my app but I'm getting an error:

Error: [$injector:unpr] Unknown provider: LocalStorageProvider <- LocalStorage <- DebugCtrl
http://errors.angularjs.org/1.3.8/$injector/unpr?p0=LocalStorageProvider%20%3C-%20LocalStorage%20%3C-%20DebugCtrl
    at http://local/Simulator/js/angular.js:63:12
    at http://local/Simulator/js/angular.js:3994:19
    at Object.getService [as get](http://local/Simulator/js/angular.js:4141:39)
    at http://local/Simulator/js/angular.js:3999:45
    at getService (http://local/Simulator/js/angular.js:4141:39)
    at Object.invoke (http://local/Simulator/js/angular.js:4173:13)
    at extend.instance (http://local/Simulator/js/angular.js:8441:21)
    at http://local/Simulator/js/angular.js:7693:13
    at forEach (http://local/Simulator/js/angular.js:331:20)
##     at nodeLinkFn (http://local/Simulator/js/angular.js:7692:11) 

The code also does not work on the actual device (Samsung 4s), AngularJS does not compile.
My code you can find here:

http://jsbin.com/degusehaze/1/edit?html,js

Thanks

**Comment by dalyc** [comment]
Sorry mate - I don't actively maintain this - it was just an experiment I did a while back. 
Your problem may have been permission based. I've added permissions that need to be added to the AndroidManifest.xml to the README.
