### ISSUE TITLE
can not find the ID of a call log to delete

### ISSUE THREAD

**Issue by woodzza** [dalyc/Cordova-CallLog-Plugin#24]
I am successfully returning a list of call log entries .. but the id does not seem to be returned. Can anyone point me in the right direction. I need the ID to be able to delete the entry:

window.plugins.calllog.delete(**id**, function (response) {
                q.resolve(response);
            }, function (error) {
                q.reject(error)
            });

**Comment by woodzza** [comment]
anyone know how to delete a call log?

**Comment by orangorangorang** [comment]
hi, sorry to bump up old thread
but can you give me the full file of demo working plugin ?

already tried for like 2 weeks for no list of log call :( thanks in advance !

**Comment by woodzza** [comment]
havent managed to get this id back, but code for the list is as follows:

`window.plugins.calllog.list("5", function (response) {
            for (var i = 0; i < response.rows.length; i++)
            {
				
				var phoneNumber = response.rows[i].number;
                		var callDuration = response.rows[i].duration;
                		var callType = response.rows[i].type;
                		var callDate = response.rows[i].date;
				var d = new Date(callDate);

				var curr_date = d.getDate();
				var curr_month = d.getMonth();
				var curr_year = d.getFullYear();
				var curr_time = d.getHours()+":"+d.getMinutes()+":"+d.getSeconds();
			
            }

        }, function (error) {
            console.log("error: " + error);
        });	`
