### ISSUE TITLE
Calling functions

### ISSUE THREAD

**Issue by PedroVB** [dalyc/Cordova-CallLog-Plugin#4]
Hi, I want to use this plugin, since I am developing a mobile application and I need to go to the last call made by the user, but I wish the call to the functions they were in JavaScript instead of Angular JS, since I do not have Angular JS never used. 
My application is based on jQuery Mobile and Cordova.
Could you help me please ??

**Comment by dalyc** [comment]
just use window.plugins.calllog

window.plugins.calllog.list :  get recent calls - takes a day limit e.g 7 is go back a week
window.plugins.calllog.show : show contact for specified phone number
window.plugins.calllog.contact : get contact details for specified phone number

**Comment by dalyc** [comment]
btw - i don't support or maintain this project - it was an experiment of mine from last year and I only leave it up on github to give others a starting point
